### PR TITLE
Bump storeon version from ^0.9.5 to ^3.0.3 and fix breaking changes

### PR DESCRIPTION
**Pull request by ruimarques**
Fixes https://github.com/storeon/angular/issues/28

### CODE REVIEW

**Comment by ruimarques** [comment]
@irustm a little help here?

I tried to bump storeon to 3.x but after fixing breaking changes, I keep getting this error which you can find in Travis:

`export 'StoreonStore' was not found in 'storeon'`

StoreonStore is indeed present in storeon, so this is some kind of build problem which i cannot solve so far.

Also tried:

- other versions of storeon, like 2.x
- updating Angular dependencies which you can also see in this PR, but made no difference.

**Comment by irustm** [comment]
thank you for PR! 

you must add 
` - npm i `
before
` - npm run test`

in `travis.ci` file

**Comment by ruimarques** [comment]
Adding `npm i` did not solve.
Trying now the cache false.

But i don't it's related to npm, think its more typescript / webpack related. I have been able to find similar related issues but so far could not solve this completely to confirm it.

**Comment by irustm** [comment]
I think I found a problem.
HarmonyImportSpecifierDependency trying to find the class StoreonStore. But there is no such function in index.js itself, the StoreonStore must be an interface

**Comment by ruimarques** [comment]
Didn't consider fixing the issue upstream but that solved it! 😄 

I proposed here a 1.x release so it follows semver. We could also consider align versions with `storeon` so we could bump this to 3.x if you think it makes sense.

Please let me know if something is missing here for a release.

**Comment by irustm** [comment]
Thanks!

**Comment by gladziu90** [comment]
Hi! when do you expect to create the release of these changes?

**Comment by irustm** [comment]
@gladziu90 thank you for reminding me! released now =)

release 1.1.0 https://www.npmjs.com/package/@storeon/angular

**Pull request merged**
