### PR TITLE
feat: ivy UseStoreon hook

### PR DESCRIPTION
**Pull request by valburyakov**
#15 

Example of using Storeon with Ivy

### CODE REVIEW

**Comment by irustm** [comment]
Hey! Thanks for this PR. 
please fix size-limit: 

  Size limit:   533 B
  Package size: 536 B

**Comment by irustm** [comment]
and I think these hooks should go with the next tag.

**Comment by valburyakov** [comment]
> and I think these hooks should go with the next tag.

you mean publish lib with @next tag ?

**Comment by irustm** [comment]
I guess yeah, just need to update the demos, and write in readme that it's all an experiment

**Comment by Svetomechc** [comment]
So, this PR also makes it impossible to use @storeon/angular without Ivy as I understand? Just making sure that this was intended, @valburyakov?

I mean, even just using the service, not Ivy hooks, fails (in production mode, debug is fine):
image

**Comment by valburyakov** [comment]
@Svetomechc You mean that even when you don't use ivy hook decorator prod build is failed with storeon ?  If yes - that seems an issue.

**Comment by Svetomechc** [comment]
@valburyakov it builds fine but errors at runtime,

**Pull request merged**
